#!/bin/bash

add-to-path () {
  local dir="$1"

  if [[ ":${PATH}:" != *:"$dir":* ]] ; then
    PATH="$dir:$PATH"
  fi
}

chromekill () {
  # shellcheck disable=SC2009
  ps ux |
      grep -E '[C]hrome Helper --type=renderer' |
      grep -Ev extension-process |
      tr -s ' ' |
      cut -d ' ' -f2 |
      xargs kill
}

follow-redirect () {
  curl -i "$1" 2>/dev/null | grep -Ei '^location: ' | cut -d ' ' -f 2
}

lolbanner () {
  banner "$1" | sed "s/#/$2/g" | sed "s/ /$3/g"
}

remove-trailing-lines () {
  sed -e :a -e '/^\n*$/{$d;N;}' -e '/\n$/ba' "$1" > "$1.sed-tmp"
  chmod --reference "$1" "$1.sed-tmp"
  mv "$1.sed-tmp" "$1"
}

tm () {
  tmux new -s "$(basename "$PWD")"
}
