#!/bin/bash

# Turn off beeps
# hash xset 2>/dev/null && xset -b

export EDITOR=vim
[[ "$(uname -s)" == Darwin ]] && export GREP_OPTIONS='--color'

alias ff-video='cp /tmp/Flash*'
alias h='hostname'
alias pyweb='python -m SimpleHTTPServer'
alias pyjson='python -m json.tool'

alias d=docker
alias dc=docker-compose

alias deflate='ruby -r zlib -e "STDOUT.write Zlib::Deflate.deflate(STDIN.read)"'
alias inflate='ruby -r zlib -e "STDOUT.write Zlib::Inflate.inflate(STDIN.read)"'
alias sumsize='xargs stat -f "%z" | paste -sd+ - | bc'

hash pbcopy 2>/dev/null || {
  alias pbcopy='xclip -selection clipboard'
  alias pbpaste='xclip -selection clipboard -o'
}

if [[ -f /usr/libexec/java_home ]] ; then
  JAVA_HOME="$(/usr/libexec/java_home)"
  export JAVA_HOME
fi

alias curl-xhr='curl -H "X-Requested-With: XMLHttpRequest"'
alias ab-xhr='ab -H "X-Requested-With: XMLHttpRequest"'

alias osx-pip-install-env='ARCHFLAGS=-Wno-error=unused-command-line-argument-hard-error-in-future'
