#!/bin/bash

# Turn off beeps
# hash xset 2>/dev/null && xset -b

export EDITOR=vim
export GREP_OPTIONS='--color'

alias ff-video='cp /tmp/Flash*'
alias h='hostname'
alias pyweb='python -m SimpleHTTPServer'
alias pyjson='python -m json.tool'

tm() {
  tmux new -s "$(basename $PWD)"
}

alias deflate="ruby -r zlib -e 'STDOUT.write Zlib::Deflate.deflate(STDIN.read)'"
alias inflate="ruby -r zlib -e 'STDOUT.write Zlib::Inflate.inflate(STDIN.read)'"
alias sumsize="xargs stat -f '%z' | paste -sd+ - | bc"

hash pbcopy 2>/dev/null || {
  alias pbcopy='xclip -selection clipboard'
  alias pbpaste='xclip -selection clipboard -o'
}

hash brew 2>/dev/null && {
  if [[ -f "$(brew --prefix)/etc/bash_completion" ]] ; then
    . "$(brew --prefix)/etc/bash_completion"
  fi
}

if [[ -f /usr/libexec/java_home ]] ; then
  export JAVA_HOME="$(/usr/libexec/java_home)"
fi

alias curl-xhr="curl -H 'X-Requested-With: XMLHttpRequest'"
alias ab-xhr="ab -H 'X-Requested-With: XMLHttpRequest'"

alias osx-pip-install-env='ARCHFLAGS=-Wno-error=unused-command-line-argument-hard-error-in-future'

# Chrome
alias chromekill="ps ux | grep '[C]hrome Helper --type=renderer' | grep -v extension-process | tr -s ' ' | cut -d ' ' -f2 | xargs kill"

self-sign() {
  local base="$1/server"
  mkdir -p "$1"
  openssl genrsa -des3 -out "$base.key" 1024
  openssl req -new -key "$base.key" -out "$base.csr"
  cp "$base.key" "$base.key.org"
  openssl rsa -in "$base.key.org" -out "$base.key"
  openssl x509 -req -days 365 -in "$base.csr" -signkey "$base.key" -out "$base.crt"
  rm "$base.csr" "$base.key.org"
}
