#!/bin/bash

export MD5_MANIFEST=".manifest.md5"
export SHA_MANIFEST=".shasum.txt"

alias chkfiles="time chkfiles-verify-files"

chkfiles-verify-files() {
  if [[ -e "$SHA_MANIFEST" ]] ; then
    if chkfiles-check-files "$SHA_MANIFEST" ; then
      echo "Updating file manifest ..."
      chkfiles-generate-manifest
    else
      echo "Files do not match the manifest"
    fi
  else
    echo "Generating new file manifest ..."
    chkfiles-generate-manifest
  fi
}

chkfiles-check-files() {
  shasum -qc "$1"
}

chkfiles-generate-manifest() {
  local tmpfile="/tmp/shasum-$RANDOM.txt"
  chkfiles-indexed-files | xargs -0 shasum -b > "$tmpfile"
  mv "$tmpfile" "$SHA_MANIFEST"
}

chkfiles-indexed-files() {
  find . -name .dropbox.cache -prune \
      -o -name .dropbox \
      -o -name .DS_Store \
      -o -name Icon \
      -o -name "$MD5_MANIFEST" \
      -o -name "$SHA_MANIFEST" \
      -o -type f -print0
}
