#!/bin/bash

CHKFILES_MD5_MANIFEST='.manifest.md5'
CHKFILES_SHA_MANIFEST='.shasum.txt'

alias chkfiles='time chkfiles-verify'

chkfiles-verify () {
  if [[ -e "$CHKFILES_SHA_MANIFEST" ]] ; then
    echo '--> checking manifest ...'
    if chkfiles-check "$@" ; then
      echo '--> updating manifest ...'
      chkfiles-update-manifest
    else
      echo '==> files do not match the manifest'
    fi
  else
    echo '--> generating new manifest ...'
    chkfiles-generate-manifest
  fi
}

chkfiles-check () {
  local manifest="${1:-$CHKFILES_SHA_MANIFEST}"

  if [[ "$(uname -s)" == Darwin ]] ; then
    shasum -qc "$manifest"
  else
    shasum -c "$manifest" | grep -Ev ': OK$'
    [[ "${PIPESTATUS[0]}" -eq 0 ]]
  fi
}

chkfiles-generate-manifest () {
  local tmpfile="/tmp/shasum-$RANDOM.txt"
  chkfiles-indexable | xargs -0 shasum -b > "$tmpfile"
  mv "$tmpfile" "$CHKFILES_SHA_MANIFEST"
}

chkfiles-update-manifest () {
  local filename

  chkfiles-unindexed | while read -r filename ; do
    shasum -b "$filename" >> "$CHKFILES_SHA_MANIFEST"
  done
}

chkfiles-indexable () {
  find . -name '.dropbox*' -prune \
      -o -name '.DS_Store' \
      -o -name 'Icon?' \
      -o -name "$CHKFILES_MD5_MANIFEST" \
      -o -name "$CHKFILES_SHA_MANIFEST" \
      -o -type f -print0
}

chkfiles-indexed () {
  cut -c 43- "$CHKFILES_SHA_MANIFEST" 2> /dev/null
}

chkfiles-diff () {
  local str="^$1 "

  diff <(chkfiles-indexed | sort) <(chkfiles-indexable | tr '\0' '\n' | sort) |
    grep -E "$str" |
    cut -c 3-
}

chkfiles-missing () {
  chkfiles-diff '<'
}

chkfiles-unindexed () {
  chkfiles-diff '>'
}
