#!/bin/bash

CKFILES_MD5_MANIFEST='.manifest.md5'
CKFILES_SHA_MANIFEST='.shasum.txt'

CKFILES_IGNORE=(
  "$CKFILES_MD5_MANIFEST"
  "$CKFILES_SHA_MANIFEST"
  '.DS_Store'
  '.dropbox*'
  'Icon?'
  'Thumbs.db'
  'ZbThumbnail.info'
)

ckfiles-ignore () {
  local file="$1"
  local name

  for name in "${CKFILES_IGNORE[@]}"; do
    if [[ "$name" == "$file" ]] ; then
      return
    fi
  done

  CKFILES_IGNORE+=("$file")
}

alias ckfiles='time ckfiles-verify'

ckfiles-verify () {
  local manifest="${1:-$CKFILES_SHA_MANIFEST}"

  if [[ -e "$manifest" ]] ; then
    echo '--> checking manifest ...'
    if ckfiles-check "$manifest" ; then
      echo '--> updating manifest ...'
      ckfiles-update-manifest "$manifest"
    else
      echo '[!] files do not match the manifest'
    fi
  else
    echo '--> generating new manifest ...'
    ckfiles-generate-manifest "$manifest"
  fi
}

ckfiles-check () {
  local manifest="${1:-$CKFILES_SHA_MANIFEST}"
  shasum --check --warn --quiet "$manifest"
}

ckfiles-generate-manifest () {
  local manifest="${1:-$CKFILES_SHA_MANIFEST}"
  local tmpfile="/tmp/ckfiles-$RANDOM.txt"

  ckfiles-indexable | xargs -0 shasum --binary > "$tmpfile"
  mv "$tmpfile" "$manifest"
}

ckfiles-update-manifest () {
  local manifest="${1:-$CKFILES_SHA_MANIFEST}"
  local filename

  ckfiles-unindexed "$manifest" | while read -r filename ; do
    shasum --binary "$filename" >> "$manifest"
  done
}

ckfiles-indexable () {
  local ignore=()
  local name

  for name in "${CKFILES_IGNORE[@]}" ; do
    ignore+=(-name "$name" -prune -o)
  done

  find . "${ignore[@]}" -type f -print0
}

ckfiles-indexed () {
  local manifest="${1:-$CKFILES_SHA_MANIFEST}"
  cut -c 43- "$manifest" 2> /dev/null
}

ckfiles-missing () {
  ckfiles-diff '<' "$1"
}

ckfiles-unindexed () {
  ckfiles-diff '>' "$1"
}

ckfiles-diff () {
  local str="^$1 "
  local manifest="${2:-$CKFILES_SHA_MANIFEST}"

  diff <(ckfiles-indexed "$manifest" | sort) \
       <(ckfiles-indexable "$manifest" | tr '\0' '\n' | sort) |
    grep -E "$str" |
    cut -c 3-
}
