#!/bin/bash

hash brew 2>/dev/null && {
  if [[ -f "$(brew --prefix)/etc/bash_completion" ]] ; then
    # shellcheck source=/dev/null
    . "$(brew --prefix)/etc/bash_completion"
  fi
}

bru() {
  brew update
  brew upgrade
  brew cask upgrade --greedy
  brew cleanup
}

bru-packages() {
  { brew list ; brew list --casks ; } | sort | uniq
}

bru-dependencies() {
  brew deps --installed | cut -d: -f2 | xargs -n1 | sort | uniq
}

bru-leaves() {
  diff <(bru-packages) <(bru-dependencies) | grep '^<' | cut -c 3-
}

bru-check-deps() {
  while read -r pkg ; do
    grep -Eq "$@" -e "^(brew|cask) '$pkg'" || echo "$pkg"
  done
}

bru-check() {
  bru-leaves | bru-check-deps ~{,/Dropbox}/Brewfile
}
