#!/bin/bash

bru-setup-completions () {
  local prefix="$1"

  if [[ -z "$prefix" ]] ; then
    return 1
  fi

  if [[ -n "$BASH_VERSION" && -f "$prefix/etc/bash_completion" ]] ; then
    # shellcheck source=/dev/null
    . "$prefix/etc/bash_completion"

  elif [[ -n "$ZSH_VERSION" ]] ; then
    FPATH="$prefix/share/zsh-completions:$FPATH"
    autoload -Uz compinit
    compinit
  fi
}

if [[ -d /opt/homebrew ]] ; then
  eval "$(/opt/homebrew/bin/brew shellenv)"
fi

bru-setup-completions "$(brew --prefix)"

bru () {
  brew update
  brew upgrade --greedy
  brew cleanup
}

bru-pin () {
  local pkg="$1"
  local version="$2"
  brew unlink "$pkg" && brew install "$pkg@$version" && brew link "$pkg@$version"
}

bru-packages () {
  { brew list --formula ; brew list --casks ; } | sort | uniq
}

bru-dependencies () {
  brew deps --installed | cut -d: -f2 | xargs -n1 | sort | uniq
}

bru-leaves () {
  diff <(bru-packages) <(bru-dependencies) | grep -E '^<' | cut -c 3-
}

bru-check-deps () {
  local pkg

  while read -r pkg ; do
    grep -Eq "$@" -e "^(brew|cask) '$pkg'" || echo "$pkg"
  done
}

bru-check () {
  bru-leaves | bru-check-deps ~{,/Dropbox}/Brewfile
}
