#!/bin/bash

alias ne='npm run-script'

export NVM_DIR="/opt/nvm"
NVM_SCRIPT="/usr/local/opt/nvm/nvm.sh"

if [ -f "$NVM_SCRIPT" ]; then
  . "$NVM_SCRIPT"
fi

function get-nvm-version {
  local version="$(echo "$NVM_BIN" | cut -d / -f 4)"
  if [ "$version" = 'versions' ]; then
    echo -n "node-"
    echo "$NVM_BIN" | cut -d / -f 6
  else
    echo "node-$version"
  fi
}

function npm-run {
  for task in $@; do
    npm run $task
    if [ $? -ne 0 ]; then
      exit 1
    fi
  done
}

hash vault 2> /dev/null && . "$( vault --initpath )"
