#!/bin/bash

# Git info in prompt
# http://railstips.org/2009/2/2/bedazzle-your-bash-prompt-with-git-info
get-git-branch() {
  ref=$(git symbolic-ref --short HEAD 2> /dev/null) || return
  echo "[$ref]"
}

RED='\e[0;31m'
GREEN='\e[0;32m'
YELLOW='\e[0;33m'
BLUE='\e[1;34m'
BLACK='\e[0;30m'
WHITE='\e[0;37m'
DEFAULT_COLOR='\e[0;39m'

PS1="$RED(\$(get-nvm-version),\$(get-chruby-version)) $BLUE\w $YELLOW\$(get-git-branch) $DEFAULT_COLOR\n$ "

# Make Vim et al use the full color palette
if [[ "$COLORTERM" == 'gnome-terminal' ]] ; then
  export TERM=xterm-256color
fi

# Change the window title of X terminals
if [[ "$TERM" == 'screen' ]] ; then
  PROMPT_COMMAND='echo -ne "\033_${USER}@${HOSTNAME%%.*}:${PWD/$HOME/~}\033\\"'
fi
