#!/bin/bash

# Git info in prompt
# http://railstips.org/2009/2/2/bedazzle-your-bash-prompt-with-git-info
get-git-branch() {
  ref=$(git symbolic-ref --short HEAD 2> /dev/null) || return
  echo "[$ref]"
}

if [[ -n "$BASH_VERSION" ]] ; then
  export PS_BLACK='\e[0;30m'
  export PS_RED='\e[0;31m'
  export PS_GREEN='\e[0;32m'
  export PS_YELLOW='\e[0;33m'
  export PS_BLUE='\e[1;34m'
  export PS_WHITE='\e[0;37m'
  export PS_DEFAULT='\e[0;39m'
  export PS_PWD='\w'
  export PS_LF='\n'
elif [[ -n "$ZSH_VERSION" ]] ; then
  export PS_BLACK='%F{black}'
  export PS_RED='%F{red}'
  export PS_GREEN='%F{green}'
  export PS_YELLOW='%F{yellow}'
  export PS_BLUE='%F{blue}'
  export PS_WHITE='%F{white}'
  export PS_DEFAULT='%f'
  export PS_PWD='%~'
  export PS_LF=$'\n'
fi

PS1="${PS_RED}(\$(get-nvm-version),\$(get-chruby-version)) ${PS_BLUE}%B${PS_PWD}%b ${PS_YELLOW}\$(get-git-branch)${PS_LF}${PS_DEFAULT}$ "

# Make Vim et al use the full color palette
if [[ "$COLORTERM" == 'gnome-terminal' ]] ; then
  export TERM=xterm-256color
fi

# Change the window title of X terminals
if [[ "$TERM" == 'screen' ]] ; then
  PROMPT_COMMAND='echo -ne "\033_${USER}@${HOSTNAME%%.*}:${PWD/$HOME/~}\033\\"'
fi
