#!/bin/bash

# Git info in prompt
# http://railstips.org/2009/2/2/bedazzle-your-bash-prompt-with-git-info
get-git-branch() {
  ref=$(git symbolic-ref --short HEAD 2> /dev/null) || return
  echo "[$ref]"
}

export COL_RED='\e[0;31m'
export COL_GREEN='\e[0;32m'
export COL_YELLOW='\e[0;33m'
export COL_BLUE='\e[1;34m'
export COL_BLACK='\e[0;30m'
export COL_WHITE='\e[0;37m'
export COL_DEFAULT='\e[0;39m'

PS1="$COL_RED(\$(get-nvm-version),\$(get-chruby-version)) $COL_BLUE\w $COL_YELLOW\$(get-git-branch) $COL_DEFAULT\n$ "

# Make Vim et al use the full color palette
if [[ "$COLORTERM" == 'gnome-terminal' ]] ; then
  export TERM=xterm-256color
fi

# Change the window title of X terminals
if [[ "$TERM" == 'screen' ]] ; then
  PROMPT_COMMAND='echo -ne "\033_${USER}@${HOSTNAME%%.*}:${PWD/$HOME/~}\033\\"'
fi
