#!/bin/bash

alias bi='ruby -S bundle config set path .bundle && ruby -S bundle install'
alias be='ruby -S bundle exec'
alias gem-uninstall='gem list | cut -d " " -f 1 | xargs gem uninstall -Iax'

CHRUBY_SCRIPT='/usr/local/share/chruby/chruby.sh'

if [[ -f "$CHRUBY_SCRIPT" ]] ; then
  # shellcheck source=/dev/null
  . "$CHRUBY_SCRIPT"
fi

get-chruby-version() {
  chruby | egrep '\*' | cut -d ' ' -f 3
}

ruby-install-with-openssl-1-0() {
  sudo ruby-install \
      -r /opt/rubies "$@" -- \
      --with-openssl-dir="$(brew --prefix openssl@1.0)"
}
