#!/bin/bash

alias bi='ruby -S bundle config set path .bundle && ruby -S bundle install'
alias be='ruby -S bundle exec'
alias gem-uninstall='gem list | cut -d " " -f 1 | xargs gem uninstall -Iax'

CHRUBY_SCRIPT='/usr/local/share/chruby/chruby.sh'

if [[ -f "$CHRUBY_SCRIPT" ]] ; then
  . "$CHRUBY_SCRIPT"
fi

get-chruby-version() {
  chruby | grep '*' | cut -d ' ' -f 3
}
