#!/bin/bash

lolbanner() {
  banner "$1" | sed "s/#/$2/g" | sed "s/ /$3/g"
}

follow-redirect() {
  curl -i "$1" 2>/dev/null | egrep -i '^location: ' | cut -d ' ' -f 2
}

remove-trailing-lines() {
  sed -e :a -e '/^\n*$/{$d;N;}' -e '/\n$/ba' "$1" > "$1.sed-tmp"
  chmod --reference "$1" "$1.sed-tmp"
  mv "$1.sed-tmp" "$1"
}
