#!/bin/bash

NUKE=.nuke
SELF=$(basename "$0")
SKIP=("$SELF" .git* tags)

for file in * ; do
  for (( i = 0; i < ${#SKIP}; i++ )) ; do
    if [[ "$file" == "${SKIP[i]}" ]] ; then
      continue 2
    fi
  done

  dest=~/."$file"
  echo "$file -> $dest"

  if [[ -f "$file/$NUKE" ]] ; then
    rsync -a --exclude "$NUKE" --delete{,-excluded} "$file/" "$dest/"

  elif [[ -d "$file" ]] ; then
    rsync -a "$file/" "$dest/"

  elif [[ -f "$file" ]] ; then
    rsync -a "$file" "$dest"
  fi
done
