#!/usr/bin/env ruby

require 'json'
require 'net/http'
require 'uri'

TOKEN = ENV['GITHUB_TOKEN']

uri   = URI('https://api.github.com/user/repos')
page  = 1
repos = []

loop do
  uri.query = "page=#{page}"
  req = Net::HTTP::Get.new(uri)
  req['Authorization'] = "Bearer #{TOKEN}"

  response = Net::HTTP.start(uri.hostname, uri.port, :use_ssl => true) do |http|
    http.request(req)
  end

  repos = JSON.parse(response.body)
  break if repos.empty?

  repos.each do |repo|
    puts repo.values_at('full_name', 'ssh_url').join(',')
  end

  page += 1
end
