#!/bin/bash

# Turn off beeps
# which xset >/dev/null && xset -b

export EDITOR=vim

alias ff-video="cp /tmp/Flash*"
alias gr="grep -riTn --color --include"
alias h="hostname"
alias pyweb="python -m SimpleHTTPServer"
alias pyjson="python -m json.tool"

which pbcopy >/dev/null || {
  alias pbcopy='xclip -selection clipboard'
  alias pbpaste='xclip -selection clipboard -o'
}

alias curl-xhr="curl -H 'X-Requested-With: XMLHttpRequest'"
alias ab-xhr="ab -H 'X-Requested-With: XMLHttpRequest'"

alias osx-pip-install-env="ARCHFLAGS=-Wno-error=unused-command-line-argument-hard-error-in-future"

# Dev tool helpers
alias be="bundle exec"
alias ne="npm run-script"
alias gem-uninstall="gem list | cut -d' ' -f1 | xargs gem uninstall -Iax"

alias chromekill="ps ux | grep '[C]hrome Helper --type=renderer' | grep -v extension-process | tr -s ' ' | cut -d ' ' -f2 | xargs kill"

# Git
alias gitd="git daemon --base-path=$HOME/projects --export-all"
alias gpl="git pull --rebase && git submodule update --init --recursive"
alias gsu="git submodule update --init --recursive"
