#!/bin/bash

# Turn off beeps
# which xset >/dev/null && xset -b

export EDITOR=vim

alias ff-video='cp /tmp/Flash*'
alias gr='grep -riTn --color --include'
alias h='hostname'
alias pyweb='python -m SimpleHTTPServer'
alias pyjson='python -m json.tool'

which pbcopy >/dev/null || {
  alias pbcopy='xclip -selection clipboard'
  alias pbpaste='xclip -selection clipboard -o'
}

alias curl-xhr='curl -H "X-Requested-With: XMLHttpRequest"'
alias ab-xhr='ab -H "X-Requested-With: XMLHttpRequest"'

alias osx-pip-install-env='ARCHFLAGS=-Wno-error=unused-command-line-argument-hard-error-in-future'

# Chrome
alias chromekill='ps ux | grep "[C]hrome Helper --type=renderer" | grep -v extension-process | tr -s " " | cut -d " " -f2 | xargs kill'
