#!/bin/bash

NVM_SCRIPT="$HOME/.nvm/nvm.sh"

if [ -f "$NVM_SCRIPT" ]; then
  . "$NVM_SCRIPT"
fi

function get-nvm-version {
  local version="$(echo "$NVM_PATH" | cut -d"/" -f5)"
  if [ "$version" = "versions" ]; then
    echo "$NVM_PATH" | cut -d"/" -f7
  else
    echo "$version"
  fi
}

which vault > /dev/null && . "$( vault --initpath )"
