#!/bin/bash

NVM_SCRIPT="$HOME/.nvm/nvm.sh"

if [ -f "$NVM_SCRIPT" ]; then
  . "$NVM_SCRIPT"
fi

function get-nvm-version {
  echo "$NVM_PATH" | cut -d"/" -f5
}

which vault > /dev/null && . "$( vault --initpath )"
