#!/bin/bash

alias ne='npm run-script'

export NVM_DIR="/opt/nvm"
NVM_SCRIPT="/usr/local/opt/nvm/nvm.sh"

if [ -f "$NVM_SCRIPT" ]; then
  . "$NVM_SCRIPT"
fi

function get-nvm-version {
  local version="$(echo "$NVM_PATH" | cut -d / -f 5 )"
  if [ "$version" = 'versions' ]; then
    echo "$NVM_PATH" | cut -d / -f 7
  else
    echo "$version"
  fi
}

function npm-run {
  for task in $@; do
    npm run $task
    if [ $? -ne 0 ]; then
      exit 1
    fi
  done
}

which vault > /dev/null && . "$( vault --initpath )"
