#!/bin/bash

# Git info in prompt
# http://railstips.org/2009/2/2/bedazzle-your-bash-prompt-with-git-info
function get-git-branch {
  ref=$(git symbolic-ref HEAD 2> /dev/null) || return
  echo "["${ref#refs/heads/}"]"
}

RED="\033[0;31m"
GREEN="\033[0;32m"
YELLOW="\033[0;33m"
BLUE="\033[1;34m"
BLACK="\033[0;30m"
WHITE="\033[0;37m"
DEFAULT_COLOR="\033[0;39m"

PS1="$RED$(hostname)(\$(get-nvm-version),\$(get-chruby-version))$BLUE \w$YELLOW\$(get-git-branch)$DEFAULT_COLOR\n$ "

# Make Vim et al use the full color palette
if [ "$COLORTERM" = "gnome-terminal" ]; then
  export TERM=xterm-256color
fi

# Change the window title of X terminals
if [ "$TERM" = "screen" ]; then
  PROMPT_COMMAND='echo -ne "\033_${USER}@${HOSTNAME%%.*}:${PWD/$HOME/~}\033\\"'
fi
